set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 100000
set -g escape-time 10
set -g focus-events on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g status on
set -g status-position bottom
set -g status-interval 2
set -g status-style "bg=#04131f,fg=#8fb6c9"

set -g status-left-length 60
set -g status-right-length 90

set -g status-left "#[fg=#04131f,bg=#5cc8ff,bold] #S #[fg=#5cc8ff,bg=#04131f] "
set -g status-right "#[fg=#8fb6c9]#(whoami) #[fg=#5cc8ff]%H:%M "

setw -g window-status-format "#[fg=#8fb6c9] #I:#W "
setw -g window-status-current-format "#[fg=#04131f,bg=#9fe7f7,bold] #I:#W "

set -g pane-border-style "fg=#12384f"
set -g pane-active-border-style "fg=#5cc8ff"

set -g message-style "bg=#12384f,fg=#d8f4ff"
set -g mode-style "bg=#5cc8ff,fg=#04131f"

setw -g clock-mode-colour "#5cc8ff"
