color_theme = "ice_mountain"
theme_background = False
truecolor = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
show_uptime = True
check_temp = True
show_coretemp = True
draw_clock = "%H:%M"
background_update = True
