[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 8
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[preview]
tab_size = 2
max_width = 1200
max_height = 1800
cache_dir = ""

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]
open = [
  { run = 'open "$@"', desc = "Open", for = "macos" }
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" }
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "application/javascript", use = "edit" },
  { mime = "inode/directory", use = "open" },
  { name = "*", use = "open" }
]
